# Configuration du thème Hexo Developer
# Theme configuration for Hexo Developer Theme

# ===== CORRECTIONS DE SUPERPOSITION =====
# Layering fixes configuration
layering_fix: true  # Activer les corrections de superposition (true/false)

# ===== PROFIL DÉVELOPPEUR =====
# Developer profile configuration
profile:
  name: "Développeur"
  title: "Full-Stack Developer"
  avatar: "/images/avatar.jpg"
  status: "Available for work"
  location: "France"
  bio: "Développeur passionné par les technologies modernes"

# ===== STACK TECHNIQUE =====
# Technology stack configuration
tech_stack:
  languages:
    - "JavaScript"
    - "TypeScript" 
    - "Python"
    - "Java"
  frameworks:
    - "React"
    - "Node.js"
    - "Express"
    - "Spring Boot"
  tools:
    - "VS Code"
    - "Git"
    - "Docker"
    - "AWS"

# ===== LIENS SOCIAUX =====
# Social links configuration
social:
  github: "your-username"
  linkedin: "your-username"
  twitter: "your-username"
  email: "your-email@example.com"

# ===== NAVIGATION =====
# Navigation menu configuration
menu:
  Accueil: /
  Projets: /projects/
  Blog: /blog/
  À propos: /about/
  Contact: /contact/

# ===== FONCTIONNALITÉS =====
# Theme features configuration
features:
  dark_mode: true           # Mode sombre
  syntax_highlighting: true # Coloration syntaxique
  search: true             # Recherche
  comments: true           # Commentaires
  analytics: true          # Analytics
  
# ===== PERFORMANCE =====
# Performance optimization
performance:
  critical_css: true       # CSS critique inline
  lazy_loading: true       # Chargement paresseux des images
  minify: true            # Minification
  compression: true       # Compression

# ===== ACCESSIBILITÉ =====
# Accessibility features
accessibility:
  skip_links: true        # Liens d'évitement
  high_contrast: true     # Support contraste élevé
  keyboard_nav: true      # Navigation clavier
  screen_reader: true     # Support lecteur d'écran

# ===== DEBUG =====
# Debug configuration (development only)
debug:
  layering_info: false    # Afficher les infos de debug layering
  performance_info: false # Afficher les infos de performance
  
# ===== COULEURS PERSONNALISÉES =====
# Custom colors (optional)
colors:
  primary: "#2563eb"      # Couleur primaire
  secondary: "#64748b"    # Couleur secondaire
  success: "#10b981"      # Couleur succès
  warning: "#f59e0b"      # Couleur avertissement
  error: "#ef4444"        # Couleur erreur

# ===== TYPOGRAPHIE =====
# Typography configuration
typography:
  font_sans: "Inter"      # Police sans-serif
  font_serif: "Georgia"   # Police serif
  font_mono: "JetBrains Mono" # Police monospace
  
# ===== LAYOUT =====
# Layout configuration
layout:
  sidebar_position: "left" # Position de la sidebar (left/right)
  container_width: "1200px" # Largeur max du conteneur
  
# ===== INTÉGRATIONS =====
# Third-party integrations
integrations:
  google_analytics: ""    # ID Google Analytics
  disqus: ""             # Nom d'utilisateur Disqus
  github_repo: ""        # Repository GitHub du site