description: >
  thomas iniguez visioli
author: thomas iniguez visioli
email: thomas.iniguez@free.fr

graph:
  twitter:            
  mastodon:           
  fediverse_creator:  ''
  github:             
  gitlab:             
  framagit:           
  pro:                
  old:                


summary:
  home: |
    Hello and welcome to my online&nbsp;space.
    Here, I explore a way to document my journey through life.

    _Enjoy!_ — Thomas
  work: >
    I combine web development, UX research and human-centered agile practices
    to put people at ease, to create a shared understanding of the _whys_ and the _whats_
    and to move from ideas to prototyping then to production.

# Newsletter Theme Configuration
newsletter:
  form_id: 'newsletter-form'
  email_input_id: 'newsletter-email'
  submit_button_id: 'newsletter-submit'
  success_message: 'Merci pour votre inscription !'
  error_message: 'Erreur lors de l inscription'
  loading_message: 'Inscription en cours...'
  placeholder_text: 'Votre adresse email'
  submit_text: 'inscription'
  enabled_pages: ['index', 'post', 'page']

links:
  - label: contenu
    href: /
  - label: suivis de site 
    href: /status/
  - label: Reading Notes
    href: /reading-notes/
  - label: veille
    href: https://feed-blush.vercel.app

  - label: About
    href: /about/


less:
  layouts:
    series-day-to-day:
      - styles/series-day-to-day.css
    series-default:
      - styles/series-default.css
  paths:
    - source/less
    - node_modules/bootstrap/less
    - node_modules/hexo-theme-thom4/source/less
    - node_modules/hexo-theme-thom4/node_modules
    - node_modules
