name: Newsletter Subscription
description: Subscribe to the newsletter to receive updates about the portfolio
title: "[NEWSLETTER] Subscription Request"
labels: ["newsletter-subscription", "automated"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in subscribing to the newsletter! Please fill out the form below.
        
        **Privacy Notice**: Your email will be encrypted and stored securely. You can unsubscribe at any time.
        
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Enter your email address to receive newsletter updates
      placeholder: your-email@example.com
    validations:
      required: true
      
  - type: dropdown
    id: frequency
    attributes:
      label: Newsletter Frequency
      description: How often would you like to receive newsletters?
      options:
        - Weekly
        - Monthly
        - Major updates only
      default: 0
    validations:
      required: true
      
  - type: checkboxes
    id: topics
    attributes:
      label: Topics of Interest
      description: Select the topics you're most interested in
      options:
        - label: Development & Programming
          value: development
        - label: Portfolio Updates
          value: portfolio
        - label: Technical Articles
          value: articles
        - label: Project Announcements
          value: projects
        - label: Industry News & Insights
          value: industry
    validations:
      required: false
      
  - type: dropdown
    id: format
    attributes:
      label: Email Format
      description: Preferred email format
      options:
        - HTML (Rich formatting)
        - Plain Text
      default: 0
    validations:
      required: true
      
  - type: checkboxes
    id: consent
    attributes:
      label: Consent & Privacy
      description: Please confirm your consent
      options:
        - label: I consent to receiving newsletters at the provided email address
          value: consent_email
          required: true
        - label: I understand that my email will be encrypted and stored securely
          value: consent_privacy
          required: true
        - label: I understand I can unsubscribe at any time
          value: consent_unsubscribe
          required: true
    validations:
      required: true
      
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information (Optional)
      description: Any additional preferences or comments
      placeholder: Optional feedback or specific interests...
    validations:
      required: false