name: Newsletter Subscription
description: Subscribe to the newsletter to receive updates about the portfolio
title: "[NEWSLETTER] Subscription Request"
labels: ["newsletter-subscription", "automated"]
assignees: []
body:
  - type: markdown
    id: header
    attributes:
      value: |
        ### Newsletter Subscription
        Thank you for your interest in our newsletter! Please fill out the form below to subscribe.

        **Privacy Notice:**
        - Your email will be encrypted and stored securely.
        - You can unsubscribe at any time by following the link in the newsletter.

  - type: input
    id: email
    attributes:
      label: Email Address
      description: Enter your email address to receive updates
      placeholder: example@domain.com
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Newsletter Frequency
      description: How often would you like to receive the newsletter?
      options:
        - Weekly
        - Bi-weekly
        - Monthly
        - Major updates only
    validations:
      required: true

  - type: checkboxes
    id: topics
    attributes:
      label: Topics of Interest
      description: Select the topics you are interested in (select all that apply)
      options:
        - label: Development & Programming
        - label: Portfolio Updates
        - label: Technical Articles
        - label: Project Announcements
        - label: Industry News & Insights

  - type: dropdown
    id: format
    attributes:
      label: Email Format
      description: Choose your preferred email format
      options:
        - HTML (Rich formatting)
        - Plain Text
    validations:
      required: true

  - type: checkboxes
    id: consent
    attributes:
      label: Consent & Privacy Agreement
      description: Please confirm the following to proceed
      options:
        - label: I consent to receiving newsletters at the provided email address
        - label: I understand my email will be encrypted and stored securely
        - label: I understand I can unsubscribe at any time
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Comments (Optional)
      description: Any additional preferences, feedback, or specific interests?
      placeholder: "Example: I'm particularly interested in AI-related projects..."
